### ISSUE TITLE
运行出现错误

### ISSUE THREAD

**Issue by jianfei96** [ljm625/unblock-china-apps#3]
30fc4ae4275276bc57e9974bc238b0d946958a51b9b83677f5a4d06bdcab5ed5
docker: Error response from daemon: driver failed programming external connectivity on endpoint hopeful_jepsen (88a5cc4292dd2901c5fb9869e45bfbe9e2452a52ee037058b34f28379e685a91): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.

**Comment by ljm625** [comment]
请检查您的server 80端口是否已经占用了，如果占用了的话。就不能用dns的那个模式

**Comment by jianfei96** [comment]
> 请检查您的server 80端口是否已经占用了，如果占用了的话。就不能用dns的那个模式

那没办法啦哈哈😄
谢大佬
